### ISSUE TITLE
main window typing repeated four times - commit 3460fdb Jul 5 21:06:33 +0100

### ISSUE THREAD

**Issue by wa1tnr** [ZanzyTHEbar/serialTerminal.com#4]
When I use /sendline utterance I get utterance four times echo'd back from the target program.

: next ." hello " cr ;  ok
next hello 
 ok
next hello 
 ok \ everything above this line entered split-terminal, single-line entry field.
/sendline next
 $  nextnext nextnext EXCEPTION(-13): Undefined Word

When I use the single-line entry above the main window, the target echo's it once and then executes what was typed (it's a Forth interpreter).

Good news:

I'm seeing good keep-up - when I do a long memory dump in Forth (which is a long text data report to the terminal) the above commit keeps up with the traffic (in advanced mode).

Test program doesn't stair-step; setting that aside for the moment.

EDIT: the input field (single top line) is robust on the (fork) upstream (advanced) version.

I pasted several lines of Forth code into that field, pressed ENTER .. and the Forth interpreter got all of it correctly read in.  Amazing.

**Comment by wa1tnr** [comment]
commit eaea642a83dd48087650cc37cc5c2bff81660202
Date:   Wed Jul 6 12:27:01 2022 +0100

>    remove extra sendline command, added support for carriage return and newline on send

The above commit causes the main window in the advanced terminal to repeat text blocks in large chunks, twice.

exhibit:

```
 warm boot message - early bird.  
 js_serterm_project - gen-exp   6 Jul 2022
          type 'warm' to reboot
 Wed Jul  6 03:07:37 UTC 2022   Feather M0 express  +NeoPixel D8  '0 npx'  '1 1 7 rgb'  '1 13 pinMode'
 4937-a3d-00b-

 warm boot message - early bird.  
 js_serterm_project - gen-exp   6 Jul 2022
          type 'warm' to reboot
 Wed Jul  6 03:07:37 UTC 2022   Feather M0 express  +NeoPixel D8  '0 npx'  '1 1 7 rgb'  '1 13 pinMode'
 4937-a3d-00b-

```

All of that appeared at once; only half of it was meant to (the target gives a detailed signon message after a warm boot using the NVIC mechanism SAMD21).

Just got up so I may be mistaken.

**Comment by ZanzyTHEbar** [comment]
Thank you - i will look at what is causing the issue.

**Comment by ZanzyTHEbar** [comment]
I found the bug, thank you for posting this issue. 

```js
if (document.getElementById("carriageReturn").checked == true)
          value = value + "\r";
if (document.getElementById("addLine").checked == true)
      printToConsoleln(value);
 // value is a string.
printToConsole(value);
```
I have to fix this logic. Will push the fix in a moment.
